<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>disable</Nullable>
    <AssemblyName>textprobe</AssemblyName>
    <RootNamespace>TextProbe</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Src\Core\WPR.Framework.Silverlight\WPR.Framework.Silverlight.csproj" />
  </ItemGroup>
</Project>
