<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows10.0.17763.0</TargetFramework>
    <Nullable>disable</Nullable>
    <AssemblyName>texfmt</AssemblyName>
    <RootNamespace>TexFmt</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <NoWarn>$(NoWarn);CS8618;CS8600;CS8602</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Src\Backends\WPR.Backend.FNA\WPR.Backend.FNA.csproj" />
  </ItemGroup>
</Project>
